### ISSUE TITLE
Why is the Prec@1 of motion cnn so low?

### ISSUE THREAD

**Issue by YanjunZhu** [jeffreyhuang1/pytorch-two-stream-cnn-ucf101#2]
Hi, the spatial cnn seems normal, but I notice that the experimental result on motion cnn is a little wired. 
It is much lower than that of two-stream cnn (81.0%) and that of TSN (87.2%). Also, in the two papers mentioned above, both temporal streams perform better than spatial streams.

**Comment by jeffreyhuang1** [comment]
Hi, I've updated the performance of motion stream, which is 78.2%, for more detail you can refer Readme !!
